### ISSUE TITLE
Improve vue-waves

### ISSUE THREAD

**Issue by guyskk** [Teddy-Zhu/vue-waves#1]
这个库现在文档不完善，另外Vue相关的代码和Waves混在一起，不好维护。
所以我自己封装了一个，代码在这: 
https://github.com/guyskk/purepage/tree/master/web/src/vue-waves

请问可以合并到这个库吗？

**Comment by Teddy-Zhu** [comment]
可以啊, 当时用的时候比较匆忙就随便整合了一下,简单可用没考虑这些
你提个pr 我合并吧

**Comment by guyskk** [comment]
好的👌

**Comment by Teddy-Zhu** [comment]
clsoed #2
