### ISSUE TITLE
Can't resolve waves.css and waves.js

### ISSUE THREAD

**Issue by bigperson** [Teddy-Zhu/vue-waves#3]
```
ERROR in ./~/vue-waves/index.js
Module not found: Error: Can't resolve './waves.css' in '...\node_modules\vue-waves'
 @ ./~/vue-waves/index.js 1:0-20

ERROR in ./~/vue-waves/index.js
Module not found: Error: Can't resolve './waves.js' in '...\node_modules\vue-waves'
 @ ./~/vue-waves/index.js 2:0-30
```

**Comment by liujinyang1994** [comment]
me too.

**Comment by jinyang1994** [comment]
@bigperson I solved, My English is not very good. Such use
1. *  
2. import Vue from 'vue';
3. import VueWaves from  '* * * * ';
4. import 'vue-waves-button/waves.css';
5. Vue.use(VueWaves);

**Comment by Teddy-Zhu** [comment]
try to update version to 0.1.1 , thx

**Comment by jinyang1994** [comment]
@Teddy-Zhu That is OK?

**Comment by Teddy-Zhu** [comment]
@liujinyang1994  i try to fix the problem , the missing files have been included in package.json
