### ISSUE TITLE
mixing import with module.exports causes error

### ISSUE THREAD

**Issue by SLRXXX** [Teddy-Zhu/vue-waves#4]

**Comment by Teddy-Zhu** [comment]
can you provide some details with the problem ?

**Comment by sainu** [comment]
Maybe I fixed it. Please review https://github.com/Teddy-Zhu/vue-waves/pull/5

**Comment by Teddy-Zhu** [comment]
@SLRXXX 
try the latest version please.
@sa-inu 
i merged the your pr , thx

**Comment by sainu** [comment]
thx
